"""create case detail table

Revision ID: a71b0dfba83c
Revises: 
Create Date: 2026-06-12 16:16:38.360211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a71b0dfba83c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('surface_texture', sa.String(length=100), nullable=True),
    sa.Column('glazed_polish', sa.String(length=100), nullable=True),
    sa.Column('incisal_translucency', sa.String(length=100), nullable=True),
    sa.Column('prepared_tooth_shade', sa.String(length=100), nullable=True),
    sa.Column('shade_guide_color', sa.String(length=255), nullable=True),
    sa.Column('material_type', sa.Text(), nullable=True),
    sa.Column('crown_bridge', sa.Text(), nullable=True),
    sa.Column('implant_type', sa.Text(), nullable=True),
    sa.Column('platform_diameter', sa.Text(), nullable=True),
    sa.Column('screw_retained', sa.Text(), nullable=True),
    sa.Column('screw_retained_hybrid', sa.Text(), nullable=True),
    sa.Column('cement_retained_ti_abutment', sa.Text(), nullable=True),
    sa.Column('zr_abutment', sa.Text(), nullable=True),
    sa.Column('implant_bar_type', sa.Text(), nullable=True),
    sa.Column('attachment_type', sa.Text(), nullable=True),
    sa.Column('additional_restorations', sa.Text(), nullable=True),
    sa.Column('design_preview', sa.Boolean(), nullable=True),
    sa.Column('additional_instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_case_details_id'), 'case_details', ['id'], unique=False)
    op.drop_index(op.f('ix_blacklist_id'), table_name='blacklist')
    op.drop_table('blacklist')
    op.drop_index(op.f('ix_material_id'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_pricing_id'), table_name='pricing')
    op.drop_table('pricing')
    op.drop_index(op.f('ix_chat_message_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.create_foreign_key(None, 'case_files', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case_files', type_='foreignkey')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_message_pkey'))
    )
    op.create_index(op.f('ix_chat_message_id'), 'chat_message', ['id'], unique=False)
    op.create_table('pricing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('material', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('belgium_dentist_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('belgium_lab_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lebanon_dentist_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lebanon_lab_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pricing_pkey'))
    )
    op.create_index(op.f('ix_pricing_id'), 'pricing', ['id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('category_pkey'))
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('material',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('material_pkey'))
    )
    op.create_index(op.f('ix_material_id'), 'material', ['id'], unique=False)
    op.create_table('blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('blacklist_pkey')),
    sa.UniqueConstraint('token', name=op.f('blacklist_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_blacklist_id'), 'blacklist', ['id'], unique=False)
    op.drop_index(op.f('ix_case_details_id'), table_name='case_details')
    op.drop_table('case_details')
    # ### end Alembic commands ###
